echo "For stage1 analysis in batch (condor), do"
echo ""
echo "cd condor"
echo ""
echo "Edit the settings in send_all.py (such as the list of samples to run over) and then submit to condor with"
echo ""
echo "python send_all.py"
echo ""
